BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "Player" (
	"id"	INTEGER,
	"nickname"	TEXT NOT NULL COLLATE NOCASE UNIQUE,
	"account_id"	TEXT NOT NULL UNIQUE,
	"country"	TEXT,
	"extra"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "TwitchChannel" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

COMMIT;
